In [20]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6" color="red">ch11. 데이터프레임과 시리즈(Pandas)</font></b>
 - pip install pandas
# 1절 판다스 패키지
 - 데이터 분석을 위해 반드시 알아야 할 패키지. numpy를 기반으로 하며, 다른 라이브러리와 잘 통합되도록 설계
 - 2차원 구조를 갖는 데이터프레임, 1차원 구조를 갖는 시리즈를 제공
 - 장점 : 데이터프레임 생성, 파일io, 레이블링, 부분데이터 추출, 크기변경(행,열의 삽입, 삭제), 데이터 분활, 병합, 데이터구조변경, 결측치 처리
 - https://pypi.python.org/pypi/pandas (package index)
 - http://pandas.pydata.org/pandas-docs/stable/api.html (API reference)

In [4]:
import pandas as pd
pd.__version__

'1.5.3'

In [7]:
data = pd.read_json('data/ch09_member1.json', encoding='euc-kr') # 기본 encoding은 utf-8
data

name  Age        Email Address
0  홍길동   30  hg@hong.com      서울
1  박길동   20  pg@hong.com      부산
2  신길동   25  sg@hong.com      대전

In [8]:
print(data)

  name  Age        Email Address
0  홍길동   30  hg@hong.com      서울
1  박길동   20  pg@hong.com      부산
2  신길동   25  sg@hong.com      대전


In [9]:
display(data)

name  Age        Email Address
0  홍길동   30  hg@hong.com      서울
1  박길동   20  pg@hong.com      부산
2  신길동   25  sg@hong.com      대전

In [13]:
member4 = pd.read_csv('data/ch09_member4.csv') # 기본 encoding은 utf-8
member4

name  Age        Email Address
0  신길동   30  sg@hong.com      서울
1  홍길동   20  ho@hong.com      수원
2  마길동   25  ma@hong.com      안양

In [17]:
member1 = pd.read_csv('data/ch09_member1.csv', header=None, names=['name','age','email','address'])
member1

name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

# 2절 데이터프레임 만들기
## 2.1 딕셔너리 리스트를 이용해서 데이터프레임 만들기

In [18]:
d = [{'kor':100, 'mat':95},{'kor':90, 'mat':99}]
df = pd.DataFrame(data=d)
df

kor  mat
0  100   95
1   90   99

In [19]:
df.to_dict() # 데이터프레임을 딕셔너리로

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 99}}

In [21]:
df.to_numpy()
df.values

array([[100,  95],
       [ 90,  99]], dtype=int64)

In [23]:
df.dtypes # 열의 타입

kor    int64
mat    int64
dtype: object

In [25]:
df.info() # (중요)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
dtypes: int64(2)
memory usage: 160.0 bytes


In [27]:
df['kor'].dtype

dtype('int64')

In [29]:
# 타입변경(열마다)
import numpy as np
df['kor'].astype(np.float64)
df['kor'].astype('float64')

0    100.0
1     90.0
Name: kor, dtype: float64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
dtypes: int64(2)
memory usage: 160.0 bytes


In [31]:
df['kor'] = df['kor'].astype('float64') # 할당

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   kor     2 non-null      float64
 1   mat     2 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 160.0 bytes


In [33]:
# 결측치가 들어가면 실수
d = [{'kor':100, 'mat':95},{'kor':90, 'mat':99},{'kor':92, 'eng':99}]
df = pd.DataFrame(data=d)
df

kor   mat   eng
0  100  95.0   NaN
1   90  99.0   NaN
2   92   NaN  99.0

In [38]:
type(np.nan)

float

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   kor     3 non-null      int64  
 1   mat     2 non-null      float64
 2   eng     1 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 200.0 bytes


In [39]:
# 결측치는 int로 형변환 불가(결측치를 대체값으로 치환 후 변환)
df['kor'] = df['kor'].astype(np.int32)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   kor     3 non-null      int32  
 1   mat     2 non-null      float64
 2   eng     1 non-null      float64
dtypes: float64(2), int32(1)
memory usage: 188.0 bytes


## 2.2 리스트를 이용해서 데이터프레임 만들기

In [41]:
kor = [100,90,95,90,65]
mat = [99,100,95,98,94]
df = pd.DataFrame({'kor':kor, 'mat':mat})
df.head(2) # 상위 2행만

kor  mat
0  100   99
1   90  100

In [42]:
np.c_[kor, mat]

array([[100,  99],
       [ 90, 100],
       [ 95,  95],
       [ 90,  98],
       [ 65,  94]])

In [44]:
df = pd.DataFrame(data=np.c_[kor, mat], columns=['국어','수학'])
df

국어   수학
0  100   99
1   90  100
2   95   95
3   90   98
4   65   94

In [45]:
df.shape

(5, 2)

In [46]:
l = [['트렌드 코리아2026', '김난도', 18000, 10],
     ['사탄탱고', '라슬로', 17820, 10],
     ['미술관 여행자', '카미유주노', 29700, 10]]
df = pd.DataFrame(l, columns=['책이름','저자','가격','할인율'])
df

책이름     저자     가격  할인율
0  트렌드 코리아2026    김난도  18000   10
1         사탄탱고    라슬로  17820   10
2      미술관 여행자  카미유주노  29700   10

In [ ]:
# %ls : ipython 매직명령어
# !dir : 쉘명령어

In [48]:
%ls "C:\ai\downloads\shareData\상가정보"

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: A014-DCD6

 C:\ai\downloads\shareData\상가정보 디렉터리

2025-10-12  오후 03:33    <DIR>          .
2025-10-12  오후 03:33    <DIR>          ..
2025-04-27  오후 11:07             1,011 [필독]파일열람방법.txt
2025-04-27  오후 11:07        61,227,944 소상공인시장진흥공단_상가(상권)정보_강원_202503.csv
2025-04-27  오후 11:07       356,572,082 소상공인시장진흥공단_상가(상권)정보_경기_202503.csv
2025-04-27  오후 11:07        93,472,559 소상공인시장진흥공단_상가(상권)정보_경남_202503.csv
2025-04-27  오후 11:07        76,425,275 소상공인시장진흥공단_상가(상권)정보_경북_202503.csv
2025-04-27  오후 11:07        40,070,868 소상공인시장진흥공단_상가(상권)정보_광주_202503.csv
2025-04-27  오후 11:07        61,715,005 소상공인시장진흥공단_상가(상권)정보_대구_202503.csv
2025-04-27  오후 11:07        41,491,092 소상공인시장진흥공단_상가(상권)정보_대전_202503.csv
2025-04-27  오후 11:07        84,550,600 소상공인시장진흥공단_상가(상권)정보_부산_202503.csv
2025-04-27  오후 11:07       294,549,483 소상공인시장진흥공단_상가(상권)정보_서울_202503.csv
2025-04-27  오후 11:07         9,303,432 소상공인시장진흥공단_상가(상권)정보_세종_202503.csv
2025-04-27  오후 11:07        28,457,489 소상공인시장진흥공단

In [52]:
pusan = pd.read_csv(r'C:\ai\downloads\shareData\상가정보\소상공인시장진흥공단_상가(상권)정보_부산_202503.csv')
pusan

상가업소번호         상호명   지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드  \
0       MA010120220700021262      경희윤한의원   NaN        Q1     보건의료      Q102   
1       MA010120220700022060        온다장터   NaN        G2       소매      G205   
2       MA010120220700004817     바른장내과의원   NaN        Q1     보건의료      Q102   
3       MA010120220700005712        과일가게   NaN        G2       소매      G205   
4       MA010120220700005946  장전언어음성심리센터   NaN        Q1     보건의료      Q104   
...                      ...         ...   ...       ...      ...       ...   
155532  MA0101202502A0111400      포마크파티룸   NaN        G2       소매      G220   
155533  MA0101202502A0114219        정옥농장   NaN        G2       소매      G204   
155534  MA0101202502A0114732     지안영어교습소   NaN        P1       교육      P105   
155535  MA0101202502A0114738      히어로스포츠   NaN        P1       교육      P106   
155536  MA0101202502A0114753          안목  부산역점        I2       음식      I201   

          상권업종중분류명 상권업종소분류코드       상권업종소분류명 표준산업분류코드  ...  \
0               의원    Q10211            한의원   Q86203  ...   
1           식료품 소매    G20506      채소/과일 소매업   G47215  ...   
2               의원    Q10201      내과/소아과 의원   Q86201  ...   
3           식료품 소매    G20506      채소/과일 소매업   G47215  ...   
4            기타 보건    Q10402         유사 의료업   Q86902  ...   
...            ...       ...            ...      ...  ...   
155532  애완동물·용품 소매    G22001  애완동물/애완용품 소매업   G47852  ...   
155533       종합 소매    G20404           슈퍼마켓   G47129  ...   
155534       일반 교육    P10501        입시·교과학원   P85501  ...   
155535       기타 교육    P10603     요가/필라테스 학원   P85612  ...   
155536          한식    I20101         백반/한정식   I56111  ...   

                           건물관리번호       건물명                    도로명주소   구우편번호  \
0       2653010300104260020017160       NaN        부산광역시 사상구 사상로 272  617816   
1       2638010300106190003013557       NaN     부산광역시 사하구 낙동대로 445-1  604848   
2       2650010400110770013005321  신세계메디컬센터        부산광역시 수영구 수영로 669  613812   
3       2638010100105300067035036      과일가게    부산광역시 사하구 괴정로270번길 20  604812   
4       2641010800102050003026429       NaN        부산광역시 금정구 금정로 169  609837   
...                           ...       ...                      ...     ...   
155532  2623010300102670003027632       NaN    부산광역시 부산진구 중앙대로 763-1  614843   
155533  2671025333102850002000001       NaN  부산광역시 기장군 장안읍 오리길 69-12  619951   
155534  2635010700114850004026754     대승프라임        부산광역시 해운대구 세실로 31  612842   
155535  2653010600100740025010100       NaN   부산광역시 사상구 가야대로366번길 22  617833   
155536  2617010100112000004006724       NaN  부산광역시 동구 중앙대로214번길 3-10  601838   

        신우편번호  동정보  층정보  호정보          경도         위도  
0       46954  NaN  NaN  NaN  128.982555  35.169059  
1       49408  NaN    1  NaN  128.969624  35.104745  
2       48243  NaN    4  NaN  129.114489  35.165574  
3       49387  NaN    1  NaN  128.990969  35.095934  
4       46283  NaN    2  NaN  129.087678  35.239736  
...       ...  ...  ...  ...         ...        ...  
155532  47251  NaN    4  NaN  129.061019  35.160630  
155533  46030  NaN  NaN  NaN  129.268218  35.369200  
155534  48111  NaN  NaN  NaN  129.179075  35.167826  
155535  47006  NaN    3  NaN  129.012518  35.150000  
155536  48733  NaN    1  NaN  129.041453  35.116696  

[155537 rows x 39 columns]

In [53]:
df.head(1) # 상위1행만

책이름   저자     가격  할인율
0  트렌드 코리아2026  김난도  18000   10

In [55]:
# 판다스 디스플레이 옵션
pd.options.display.max_columns = 39 # 39열까지 display가능. 기본값은 20
pd.options.display.max_rows = 70    # 70행까지 display가능. 기본값은 60
df.head(1) # 상위1행만

책이름   저자     가격  할인율
0  트렌드 코리아2026  김난도  18000   10

In [56]:
df.head(1).T

0
책이름  트렌드 코리아2026
저자           김난도
가격         18000
할인율           10

## 2.3 read_csv

In [64]:
# help(pd.read_csv)
#pd.read_csv() # 함수 안에서 shift+tab+tab
pd.read_csv?

In [65]:
# (1) CSV 파일 불러오기(기본값)
member = pd.read_csv('data/ch11_member.csv',
                    #, encoding='utf-8', sep=',', comment주석처리X
                    )
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      int64 
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes


In [66]:
# 문자형으로 읽어들인 Birth를 datetime형으로
# 형변환 : astype('int64'), astype('datetime64' : 비추)
#         to_datetime()함수
# member['Birth'].astype('datetime64') 비추
member['Birth'] = pd.to_datetime(member['Birth'])
member.head(1)

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [67]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     6 non-null      object        
 1   Age      6 non-null      int64         
 2   Email    6 non-null      object        
 3   Address  6 non-null      object        
 4   Birth    6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 368.0+ bytes


In [68]:
import numpy as np
member['Age'] = member['Age'].astype(np.int16)
member.dtypes

Name               object
Age                 int16
Email              object
Address            object
Birth      datetime64[ns]
dtype: object

In [59]:
# (2) 특정행을 제외하고 csv 파일 읽어오기
member = pd.read_csv('data/ch11_membercp949.csv', 
                     encoding='cp949', skiprows=[1,6]) # 1,6행 제외하고 읽기(시작은 1부터)
member

Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [60]:
# (3) 상위 몇행만 stpe문자는 ,아닌 csv파일 읽기
member = pd.read_csv('data/ch11_membersep.csv', nrows=5, # 상위5행만
                     sep='|')
member

Name  Age          Email  Address       Birth
0  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구  1999-01-30

In [63]:
# (4) 주석(#)제외, datetime형 필드를 지정하여 csv파일 읽기
member = pd.read_csv('data/ch11_membertab.csv', sep='\t', 
                     comment='#', # 주석제외
                     parse_dates=['Birth']) # datetime64형으로 읽어올 필드 지정
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     5 non-null      object        
 1   Age      5 non-null      int64         
 2   Email    5 non-null      object        
 3   Address  5 non-null      object        
 4   Birth    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 328.0+ bytes


## 2.4 패키지에서 가져오기 : iris데이터
 - iris 가져오기 방법1 : sklearn(머신러닝 패키지)
 - iris 가져오기 방법2 : statsmodels (R 데이터)
 - iris 가져오기 방법3 : seaborn(시각화패키지)
### 2.4.1 iris 방법1 : sklearn
 - sklearn.datasets 모듈 데이터(iris)를 데이터 프레임으로 변환

In [74]:
from sklearn import datasets # 머신러닝 학습 데이터셋 제공
# sklearn 패키지에서 제공하는 데이터셋은 딕셔너리형식
iris = datasets.load_iris()
print(type(iris)) # _bunch.Bunch 타입(딕셔너리 상속받은 타입) 딕셔너리처럼 동작
# print(iris.DESCR) # 설명
print(iris.keys())

<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [75]:
iris.data # 독립변수
iris['data'][:3] # 상위 3행

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [76]:
iris.feature_names # 열이름(빈칸과 특수문자는 제거하는게 좋음)

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [80]:
[col[:-5].replace(' ','_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [82]:
iris.target # ML/DL 학습시 타겟변수(종속변수)
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [83]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [84]:
iris.target_names[iris.target] # 데이터테이블에 쓸 타겟변수(가장 오른쪽 열)

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [86]:
#독립변수
data = iris.data
#종속변수
target = iris.target_names[iris.target].reshape(-1,1)
print(data[:3], target[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]] [['setosa']
 ['setosa']
 ['setosa']]


In [87]:
print('독립변수 shape :', data.shape)
print('타겟변수 shape :', target.shape)

독립변수 shape : (150, 4)
타겟변수 shape : (150, 1)


In [88]:
df = pd.DataFrame(np.hstack((data, target)), columns=iris.feature_names + ['species'])
df

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)  \
0                 5.1              3.5               1.4              0.2   
1                 4.9              3.0               1.4              0.2   
2                 4.7              3.2               1.3              0.2   
3                 4.6              3.1               1.5              0.2   
4                 5.0              3.6               1.4              0.2   
..                ...              ...               ...              ...   
145               6.7              3.0               5.2              2.3   
146               6.3              2.5               5.0              1.9   
147               6.5              3.0               5.2              2.0   
148               6.2              3.4               5.4              2.3   
149               5.9              3.0               5.1              1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [94]:
# df.sepal length (cm) # 사용불가
# df['sepal length (cm)']
df.columns = [col[:-5].replace(' ', '_') for col in iris.feature_names] + ['species']
df.head(1)

sepal_length sepal_width petal_length petal_width species
0          5.1         3.5          1.4         0.2  setosa

In [95]:
df.sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: object

In [96]:
# 2. 독립변수, 종속변수를 따로 데이터프레임으로 생성-> 두 데이터프엠을 연결
X = pd.DataFrame(iris.data, 
                 columns=[col[:-5].replace(' ', '_') for col in iris.feature_names])
X.head(1)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [97]:
y = pd.DataFrame(iris.target_names[iris.target], columns=['species'])
y.head(1)

species
0  setosa

In [98]:
print('X의 shape :', X.shape)
print('y의 shape :', y.shape)
print('X의 index :', X.index)
print('y의 index :', y.index)

X의 shape : (150, 4)
y의 shape : (150, 1)
X의 index : RangeIndex(start=0, stop=150, step=1)
y의 index : RangeIndex(start=0, stop=150, step=1)


In [99]:
iris_df = pd.concat( [X, y], axis=1 ) # 두개의 데이터프레임을 열로 연결
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
